# WARNING: Upgrade the k8s cluster can be risky. Make sure you know what you are doing.
# Read the guide: 'op/upgrade.md' .

# update masters
- hosts: 
  - kube-master
  roles:
  - kube-master
  - kube-node

# update nodes
- hosts: 
  - kube-node
  roles:
  - { role: kube-node, when: "inventory_hostname not in groups['kube-master']" }
